basePath: /
definitions:
  models.Answer:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      questionID:
        type: integer
      text:
        maxLength: 500
        minLength: 3
        type: string
      userID:
        type: string
    required:
    - text
    type: object
  models.Question:
    properties:
      answers:
        items:
          $ref: '#/definitions/models.Answer'
        type: array
      createdAt:
        type: string
      id:
        type: integer
      text:
        maxLength: 500
        minLength: 3
        type: string
    required:
    - text
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a question service.
  title: Question Service API
  version: "1.0"
paths:
  /answers/{id}:
    delete:
      description: Delete an answer by its ID
      parameters:
      - description: Answer ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: Delete an answer by ID
      tags:
      - answers
    get:
      description: Get an answer by its ID
      parameters:
      - description: Answer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Answer'
      summary: Get an answer by ID
      tags:
      - answers
  /questions:
    get:
      description: Get a list of all questions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Question'
            type: array
      summary: Get all questions
      tags:
      - questions
    post:
      consumes:
      - application/json
      description: Create a new question with the input payload
      parameters:
      - description: Question to create
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Question'
      summary: Create a new question
      tags:
      - questions
  /questions/{id}:
    delete:
      description: Delete a question by its ID
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: Delete a question by ID
      tags:
      - questions
    get:
      description: Get a question by its ID
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Question'
      summary: Get a question by ID
      tags:
      - questions
  /questions/{id}/answers:
    post:
      consumes:
      - application/json
      description: Create an answer for a specific question
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: integer
      - description: Answer to create
        in: body
        name: answer
        required: true
        schema:
          $ref: '#/definitions/models.Answer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Answer'
      summary: Create an answer for a question
      tags:
      - answers
swagger: "2.0"
